use_frameworks!

platform :ios, '12.1'

target 'PartnerOneSDK_Example' do
  pod 'PartnerOneSDK', :path => '../'
  
  target 'PartnerOneSDK_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "FaceTecSDK"
            target.build_configurations.each do |config|
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = './**'
            end
        end
    end
end
