use_frameworks!

platform :ios, '12.1'

target 'PartnerOneSDK_Example' do
  pod 'PartnerOneSDK/Unico', :path => '../'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper', '~> 3.5'
  
  target 'PartnerOneSDK_Tests' do
    inherit! :search_paths
  end
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == "FaceTecSDK"
#            target.build_configurations.each do |config|
#                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = '${PODS_ROOT}/**'
#            end
#        end
#    end
#end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
end
