import UIKit
import FaceTecSDK

final class FacialScanViewController: UIViewController, FaceTecFaceScanProcessorDelegate, URLSessionDelegate {
  
  //MARK: - Properties
  
  var viewModel: ScanViewModel
  var helper = PartnerHelper()
  
  private var latestExternalDatabaseRefID: String = ""
  private var latestSessionResult: FaceTecSessionResult!
  private var latestIDScanResult: FaceTecIDScanResult!
  private var sessionResult: FaceTecSessionResult?
  private var resultCallback: FaceTecFaceScanResultCallback?
  private var latestProcessor: Processor!
  private var utils: SampleAppUtilities?
  
  var processorResponse: (() -> Void)?
  
  private let activity: UIActivityIndicatorView = {
    let activity = UIActivityIndicatorView()
    activity.style = .whiteLarge
    activity.startAnimating()
    activity.translatesAutoresizingMaskIntoConstraints = false
    return activity
  }()
  
  //MARK: - init
  
  init(viewModel: ScanViewModel) {
    self.viewModel = viewModel
    super.init(nibName: nil, bundle: nil)
  }
  
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
  }
  
  //MARK: - View Lifecycle
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    navigationItem.hidesBackButton = true
    view.backgroundColor = .white
    view.addSubview(activity)
    activity.centerXAnchor.constraint(equalTo: view.centerXAnchor).isActive = true
    activity.centerYAnchor.constraint(equalTo: view.centerYAnchor).isActive = true
    
    FaceTec.initialize()
    faceTecLivenessData()
    helper.faceTecAnalisys(self)
  }
  
  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    setupFaceTec()
  }
}

//MARK: - Private Functions

extension FacialScanViewController {
  func setupFaceTec() {
    
    FaceTec.sdk.initializeInProductionMode(productionKeyText: Config.ProductionKeyText,
                                           deviceKeyIdentifier: Config.DeviceKeyIdentifier,
                                           faceScanEncryptionKey: Config.PublicFaceScanEncryptionKey)
    Config.initializeFaceTecSDKFromAutogeneratedConfig(completion: { initializationSuccessful in
      Config.displayLogs()
      
      Config.ProductionKeyText = self.helper.faceTecProductionKeyText
      Config.DeviceKeyIdentifier = self.helper.faceTecDeviceKeyIdentifier
      Config.PublicFaceScanEncryptionKey = self.helper.faceTecPublicFaceScanEncryptionKey
      
      self.initializeProcessor()
    })
  }
  
  func processSessionWhileFaceTecSDKWaits(sessionResult: FaceTecSessionResult,
                                          faceScanResultCallback: FaceTecFaceScanResultCallback) {
    print(sessionResult.auditTrailCompressedBase64?[0] ?? "")
  }
  
  func onFaceTecSDKCompletelyDone() {
    print("Escaneamento Completo. Navegando para Status!")
  }
  
  func onComplete() {
    
    helper.navigateToStatus?()
  }
  
  func getLatestExternalDatabaseRefID() -> String {
    return latestExternalDatabaseRefID;
  }
  
  func setLatestSessionResult(sessionResult: FaceTecSessionResult) {
    latestSessionResult = sessionResult
  }
  
  func initializeProcessor() -> Processor {
    return LivenessCheckProcessor(sessionToken: helper.createUserAgentForSession(), fromViewController: self)
  }
  
  public func createUserAgentForNewSession() -> String {
    return FaceTec.sdk.createFaceTecAPIUserAgentString("")
  }
  
  public func createUserAgentForSession(_ sessionId: String) -> String {
    return FaceTec.sdk.createFaceTecAPIUserAgentString(sessionId)
  }
  
  public func getLowQualityAuditTrailImage() -> String {
    return sessionResult?.lowQualityAuditTrailCompressedBase64![0] ?? ""
  }
  
  public func faceTecLivenessData(faceScanBase: String = "",
                                  auditTrailImage: String = "",
                                  lowQualityAuditTrailImage: String = "") {
    
    processorResponse = {
      self.helper.getFaceScan(faceScanBase)
      self.helper.getAuditTrailImage(auditTrailImage)
      self.helper.getLowQualityAuditTrailImage(lowQualityAuditTrailImage)
      
      self.helper.waitingFaceTecResponse?(faceScanBase, auditTrailImage, lowQualityAuditTrailImage)
      
      print("@! >>> Processamento finalizado.")
    }
  }
}
