//
// FaceTec Device SDK config file.
// Auto-generated via the FaceTec SDK Configuration Wizard
//
import UIKit
import Foundation
import FaceTecSDK

class Config {
  
  static let DeviceKeyIdentifier = PartnerHelper().faceTecDeviceKeyIdentifier()
  
  static let BaseURL = PartnerHelper().faceTecBaseURL()
  
  static let PublicFaceScanEncryptionKey = PartnerHelper().faceTecPublicFaceScanEncryptionKey()
  
  static let ProductionKeyText = PartnerHelper().faceTecProductionKeyText()
  
  static func displayLogs() {
    print("@! >>> FaceTec_BaseURL: ", Config.BaseURL)
    print("@! >>> FaceTec_DeviceKeyIdentifier: ", Config.DeviceKeyIdentifier)
    print("@! >>> FaceTec_PublicFaceScanEncryptionKey: ", Config.PublicFaceScanEncryptionKey)
    print("@! >>> FaceTec_ProductionKeyText: ", Config.ProductionKeyText)
  }
  
  //    static let DeviceKeyIdentifier = "dioxhbQHfJHmnHTzJ40hCiUm3FR0IkXY"
  
  //    static let BaseURL = "https://digital-id.webdatadome.com/api"
  
  //    static let PublicFaceScanEncryptionKey =
  //        "-----BEGIN PUBLIC KEY-----\n" +
  //        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5PxZ3DLj+zP6T6HFgzzk\n" +
  //        "M77LdzP3fojBoLasw7EfzvLMnJNUlyRb5m8e5QyyJxI+wRjsALHvFgLzGwxM8ehz\n" +
  //        "DqqBZed+f4w33GgQXFZOS4AOvyPbALgCYoLehigLAbbCNTkeY5RDcmmSI/sbp+s6\n" +
  //        "mAiAKKvCdIqe17bltZ/rfEoL3gPKEfLXeN549LTj3XBp0hvG4loQ6eC1E1tRzSkf\n" +
  //        "GJD4GIVvR+j12gXAaftj3ahfYxioBH7F7HQxzmWkwDyn3bqU54eaiB7f0ftsPpWM\n" +
  //        "ceUaqkL2DZUvgN0efEJjnWy5y1/Gkq5GGWCROI9XG/SwXJ30BbVUehTbVcD70+ZF\n" +
  //        "8QIDAQAB\n" +
  //        "-----END PUBLIC KEY-----"
  
  //    static let ProductionKeyText = "appId      = *\n" +
  //    "expiryDate = 2023-02-10\n" +
  //    "key        = 003045022064245be6a70ccac99d3f744cbafdb8fdf416aafa45fb42f90d907465852246ef022100922a1b802481c572d4b1bef5d86d8dd70055d16164fff61a486796e7e7a68fed\n"
  
  
  
  // -------------------------------------
  // Convenience method to initialize the FaceTec SDK.
  // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on the Keys issued to your Apps.
  static func initializeFaceTecSDKFromAutogeneratedConfig(completion: @escaping (Bool)->()) {
    FaceTec.sdk.initializeInProductionMode(productionKeyText: ProductionKeyText, deviceKeyIdentifier: Config.DeviceKeyIdentifier, faceScanEncryptionKey: Config.PublicFaceScanEncryptionKey, completion: { initializationSuccessful in
      completion(initializationSuccessful)
    })
  }
  
  // -------------------------------------
  // This app can modify the customization to demonstrate different look/feel preferences
  // NOTE: This function is auto-populated by the FaceTec SDK Configuration Wizard based on your UI Customizations you picked in the Configuration Wizard GUI.
  public static func retrieveConfigurationWizardCustomization() -> FaceTecCustomization {
    return FaceTecCustomization()
  }
  
  public static func retrieveLowLightConfigurationWizardCustomization() -> FaceTecCustomization {
    return FaceTecCustomization()
  }
  
  public static func retrieveDynamicDimmingConfigurationWizardCustomization() -> FaceTecCustomization {
    return FaceTecCustomization()
  }
  
  static var currentCustomization: FaceTecCustomization = retrieveConfigurationWizardCustomization()
  static var currentLowLightCustomization: FaceTecCustomization = retrieveLowLightConfigurationWizardCustomization()
  static var currentDynamicDimmingCustomization: FaceTecCustomization = retrieveDynamicDimmingConfigurationWizardCustomization()
  
  // -------------------------------------
  // Boolean to indicate the FaceTec SDK Configuration Wizard was used to generate this file.
  // In this Sample App, if this variable is true, a "Config Wizard Theme" will be added to this App's Design Showcase,
  // and choosing this option will set the FaceTec SDK UI/UX Customizations to the Customizations that you selected in the
  // Configuration Wizard.
  static let wasSDKConfiguredWithConfigWizard = false
}
